Add docstring for `genlist` function and installation/usage instructions in README.md
QuantumBFS/YaoPastaQ.jl pull request #17
Opened 2021-12-24 22:47 UTC by VarLad

2021-12-24 22:50 UTC, VarLad commented
@Roger-luo I think I should've deleted the previous branch and forked it again. 
If its an issue, do tell. 

Otherwise, its good to merge. :crossed_fingers:

2021-12-25 00:40 UTC, Roger-luo requested changes

2021-12-25 00:40 UTC, Roger-luo commented on src/YaoPastaQ.jl
> +Returns the PastaQ input list from Yao's QBIR
You need to put function signature in the docstring

2021-12-25 00:40 UTC, Roger-luo commented on README.md
> +julia> add https://github.com/QuantumBFS/YaoPastaQ.jl
Can you just use the README template in Configurations.jl? This would be more consistent

2021-12-25 00:46 UTC, VarLad commented on README.md
> +julia> add https://github.com/QuantumBFS/YaoPastaQ.jl
Thanks for pointing it out, will do both as soon as possible (after I fetch some sleep) 😃

2022-01-28 00:53 UTC, VarLad commented
Sorry, I'm aware that I should've done this in 2 PRs, but it wasn't much so I just stuffed the new gates and fixes in here :grimacing:

2022-01-28 01:15 UTC, Roger-luo approved these changes
LGTM

2022-01-28 01:26 UTC, merged