Registers for PastaQ
QuantumBFS/YaoPastaQ.jl pull request #4
Opened 2021-05-20 09:25 UTC by VarLad

I guess I made the PR, but of course it doesn't work

2021-05-20 09:27 UTC, VarLad commented
You told me to overload `Yao.apply!`
But I guess that doesn't mean making direct changes to Yao.jl.....

2021-05-20 17:43 UTC, Roger-luo commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
so first I'd like you to read throught the implementation here: https://github.com/QuantumBFS/YaoArrayRegister.jl/blob/9dd04982359435bca2f93679c23824420229799b/src/register.jl#L3-L9

2021-05-21 07:43 UTC, VarLad commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
@Roger-luo Its working but since I didn't include AbstractRegister as a supertype, I guess you can call this "incomplete"?

Its giving an error, for every way I try to implement the AbstractRegister supertype
Something like,
```
julia> struct PastaQRe{B, State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister{B}
           state::State
       end

julia> PastaQRe(3)
ERROR: MethodError: no method matching PastaQRe(::Int64)
Stacktrace:
 [1] top-level scope
   @ REPL[13]:1

julia> PastaQRe{3}
PastaQRe{3, State} where State<:Union{ITensors.MPO, ITensors.MPS}

julia> PastaQRe{3}(productstate(3))
ERROR: MethodError: no method matching (PastaQRe{3, State} where State<:Union{ITensors.MPO, ITensors.MPS})(::ITensors.MPS)
Stacktrace:
 [1] top-level scope
   @ REPL[15]:1
  ```
  I guess this is a syntax/implementation error. If you've some advice, idea, that would be welcome

2021-05-21 17:39 UTC, VarLad commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
@Roger-luo Any hints? I'm think it might be wrong.....

2021-05-21 19:18 UTC, VarLad commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
@Roger-luo A review is required here

Just want to check if this is the right direction

2021-05-21 21:39 UTC, VarLad commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
Should I proceed to wrapping other methods from https://github.com/GTorlai/PastaQ.jl/blob/acd5e2d85199f26c8ff840cdeee9aac98c79dbb2/src/circuits/productstates.jl as well?

2021-05-22 16:55 UTC, VarLad commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
> so first I'd like you to read throught the implementation here: https://github.com/QuantumBFS/YaoArrayRegister.jl/blob/9dd04982359435bca2f93679c23824420229799b/src/register.jl#L3-L9

@Roger-luo I've read through the implementation
What would be step 2?

2021-05-23 20:41 UTC, Roger-luo commented on src/YaoPastaQ.jl
> +struct PastaQReg{State <: Union{PastaQ.MPS, PastaQ.MPO}} <: AbstractRegister
you are missing the type parameters in `AbstractRegister`, it should be `AbstractRegister{1}` for the PastaQ case where the batch size is always 1.

2021-05-23 20:42 UTC, Roger-luo commented on src/YaoPastaQ.jl
> +YaoBase.apply!(r::PastaQReg, x::AbstractBlock) = runcircuit(r.state, genlist(x))
you should return the register `r` since `apply!` has this convention.

2021-05-23 21:07 UTC, Roger-luo commented
I believe you missed a few more interfaces to overload, please refer to the `ArrayReg` again.

2021-05-23 21:14 UTC, VarLad commented
> I believe you missed a few more interfaces to overload, please refer to the ArrayReg again.

I guess you mean the equivalent for 

`function ArrayReg{B}(raw::MT) where {B,T,MT<:AbstractMatrix{T}}` 

`ArrayReg(bitstr::BitStr) = ArrayReg(ComplexF64, bitstr)`

and

`ArrayReg(r::ArrayReg{B}) where {B} = ArrayReg{B}(copy(r.state))`

to be specific?

2021-05-23 21:19 UTC, Roger-luo commented
here is a list of the interfaces, please try to overload them as much as possible (if you find corresponding interface applicable to PastaQ case)

https://github.com/QuantumBFS/YaoAPI.jl/blob/master/src/registers.jl

2021-05-25 19:48 UTC, VarLad commented
@Roger-luo Requesting review
I couldn't implement some functions as PastaQ still doesn't provide that functionality (yet)
While some investigating into ITensors library _can_ make them work, but its better to implement those functions in PastaQ then wrapping them here

2021-05-26 14:21 UTC, Roger-luo requested changes
there are only some small things left, please fix them and make sure the tests pass on CI then this PR will be good to merge

2021-05-26 14:21 UTC, Roger-luo commented on test/runtests.jl
> +    @test nqubits(PastaQReg(3)) isa Int64
please check the actual value

2021-05-26 14:21 UTC, Roger-luo commented on src/YaoPastaQ.jl
> +function YaoBase.measure!(x::PastaQReg, nshots::Int=1024)
measure is a special method doesn't follow the `!` convention, it should return the samples

2021-05-26 14:21 UTC, Roger-luo commented on src/YaoPastaQ.jl
> +    display(getsamples(x.state, nshots))
please remove all the display functions

2021-05-26 15:04 UTC, mtfishman commented on src/YaoPastaQ.jl
> +YaoBase.apply!(r::PastaQReg, x::AbstractBlock) = runcircuit(r.state, genlist(x))
Does this need to be in-place? It would be easy enough to add `runcircuit!`.

2021-05-26 15:06 UTC, mtfishman commented
> @Roger-luo Requesting review
> I couldn't implement some functions as PastaQ still doesn't provide that functionality (yet)
> While some investigating into ITensors library _can_ make them work, but its better to implement those functions in PastaQ then wrapping them here

Which functionality is missing in PastaQ that are needed for the `AbstractRegister` interface? We could start a list of features that should be added.

2021-05-26 15:11 UTC, Roger-luo commented
> Which functionality is missing in PastaQ that are needed for the AbstractRegister interface? We could start a list of features that should be added.

I haven't looked into that, but I think it's mainly related to batch execution and the LDT format register (which allows you represent purified mix-state), I don't think these are big deal tho.

2021-05-26 15:20 UTC, mtfishman commented
What do you mean by "batch execution"? And could you expand a bit more on what the LDT format is? You just mean split the qubits of a state into physical qubits and environment qubits? Agreed that these don't seem very important for getting basic functionality working.

Also to get a big picture of what is going on in this PR, does this basically just allow you to use PastaQ as a backend for running circuits using the Yao interface?

2021-05-26 15:45 UTC, VarLad commented on src/YaoPastaQ.jl
> +YaoBase.apply!(r::PastaQReg, x::AbstractBlock) = runcircuit(r.state, genlist(x))
PastaQ doesn't have a `runcircuit!`

2021-05-26 15:46 UTC, VarLad commented
@Roger-luo Recheck

2021-05-26 15:49 UTC, mtfishman commented on src/YaoPastaQ.jl
> +YaoBase.apply!(r::PastaQReg, x::AbstractBlock) = runcircuit(r.state, genlist(x))
Yes, I meant it would be easy to add to PastaQ if needed.

2021-05-26 15:51 UTC, VarLad commented
Why's the CI failing to precompile the packages....?
Is it because we're running it on Julia nightly?

2021-05-26 15:56 UTC, VarLad commented
> Yes, but this is for the old QBIR (aka YaoBlocks) in our paper, not the new YaoIR, QBIR will be deprecated when YaoIR becomes mature. The algorithms in QuAlgorithmZoo etc. should be runnable using PastaQ after this.

So.... someone will have to rewrite this stuff in the future? :eyes:

2021-05-26 16:17 UTC, Roger-luo commented
> So.... someone will have to rewrite this stuff in the future? 👀

no, this package is for YaoBlocks. the design of YaoBlocks is considered mature and should stay what it is forever. 

It may takes one or two more years to get YaoCompiler mature enough for a 1.0, so we need this package.

2021-05-26 16:18 UTC, Roger-luo commented
> Why's the CI failing to precompile the packages....?
> Is it because we're running it on Julia nightly?

Yes, let's change the CI to 1

2021-05-26 16:18 UTC, Roger-luo commented
change the `'nightly'` to `'1'` here: https://github.com/QuantumBFS/YaoPastaQ.jl/blob/master/.github/workflows/CI.yml#L13

2021-05-26 17:49 UTC, VarLad commented
@Roger-luo  Done!
Ready to merge!

2021-05-26 17:51 UTC, Roger-luo commented
The testcov is not great, please try to push it to at least over 80%

2021-05-26 18:27 UTC, VarLad commented
@Roger-luo Done! Ready to merge, I guess

2021-05-26 18:31 UTC, Roger-luo commented
cool, thanks!

2021-05-26 18:32 UTC, merged